### ISSUE TITLE
Visualization of strong components for all of NZ

### ISSUE THREAD

**Issue by kaneplusplus** [s-u/nz-commute-graph#1]
The file `artifacts/strong-components-and-stat-distr.rds` contains a `data.frame` with 3 columns, the location index (called `name` same ordering as in trans-matrix.rds), the strong component it belongs to (`component` column), and the stationary distribution. Please create a map with each component having it's own color.

**Comment by s-u** [comment]
@kaneplusplus I think you may not have pushed the files?
